workflows:
  flutter-shorebird-workflow:
    name: Flutter iOS with Shorebird
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: app-store-connect

    environment:
      flutter: 3.24.1
      flutter: stable
      xcode: latest

      vars:
        BUNDLE_ID: "com.innove.solucoes"
        APP_STORE_APPLE_ID: 6748886024
        XCODE_SCHEME: "Runner"
        SHOREBIRD_VERSION: "latest"
        SHOREBIRD_TOKEN: "eyJyZWZyZXNoX3Rva2VuIjoiMS8vMGh0dk84VmpDX2FxV0NnWUlBUkFBR0JFU053Ri1MOUlyOVZsRWZ5Sk5ndmlrZkVoWWRFYXV3NXRqQ002OFpkMW1kT0VBaF9PZlNFR2JMN21HeGVkTTNweWRyc0FqbWJFV2ZnUSIsImF1dGhfcHJvdmlkZXIiOiJnb29nbGUifQ=="

      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID

    scripts:
      - name: Install Shorebird
        script: |
          curl https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird --version

      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Build Release IPA with Shorebird
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird release ios --flutter-version=3.29.0 --verbose -- --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
